In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.utils import to_categorical
import tensorflow as tf
from tensorflow import keras

In [2]:
df=pd.read_csv("/content/drive/MyDrive/github/collegeproject/datasets/south_crops.csv")
df.columns

Index(['State_Name', 'District_Name', 'Crop_Year', 'Season', 'Area',
       'Production', 'Temperature', 'PH', 'Rainfall', 'Sowing Temp',
       'Harvest Temp', 'Phosphorous', 'Nitrogen', 'Potash', 'crop'],
      dtype='object')

In [4]:
df=df.iloc[:,[4,6,8,9,10]]

In [5]:
df.columns

Index(['Area', 'Temperature', 'Rainfall', 'Sowing Temp', 'Harvest Temp'], dtype='object')

In [6]:
df.describe()

                Area   Temperature      Rainfall   Sowing Temp  Harvest Temp
count   19354.000000  19354.000000  19354.000000  19354.000000  19354.000000
mean    17754.839085     25.310872     80.548313     26.460252     26.319801
std     44034.176532      4.515875     55.583544      4.596210      6.472186
min         0.240000     14.062558      7.501110     15.002345     14.003701
25%       237.000000     22.293138     54.321871     23.133913     21.010482
50%      2146.500000     25.380890     67.638047     26.346951     24.875361
75%     14327.250000     28.275284     92.931267     29.636535     31.512740
max    877029.000000     39.895564    299.865346     39.997403     39.999557

In [3]:
df.shape

(19354, 15)

In [ ]:
df['crop'].unique()

array(['arhar_tur', 'bajra', 'coriander', 'cotton_lint', 'dry_chillies',
       'gram', 'groundnut', 'jowar', 'maize_k', 'maize_r',
       'moong_green_gram', 'onion', 'potato', 'ragi', 'rice', 'sugarcane',
       'sunflower', 'turmeric', 'urad', 'wheat', 'linseed', 'safflower',
       'rapeseed_mustard', 'cowpea_lobia'], dtype=object)

In [ ]:
df.dtypes

State_Name        object
District_Name     object
Crop_Year          int64
Season            object
Area             float64
Production       float64
Temperature      float64
PH               float64
Rainfall         float64
Sowing Temp      float64
Harvest Temp     float64
Phosphorous      float64
Nitrogen         float64
Potash           float64
crop              object
dtype: object

In [ ]:
crops=pd.read_csv("/content/drive/MyDrive/github/collegeproject/datasets/south_crops.csv")

In [ ]:
crops.columns

Index(['State_Name', 'District_Name', 'Crop_Year', 'Season', 'Area',
       'Production', 'Temperature', 'PH', 'Rainfall', 'Sowing Temp',
       'Harvest Temp', 'Phosphorous', 'Nitrogen', 'Potash', 'crop'],
      dtype='object')

In [ ]:
# Get the unique values of the column you want to split the data by
column_values = crops['crop'].unique()
# Loop over the unique values of the column
for value in column_values:
    # Create a dataframe for each unique value
    value_df = crops[crops['crop'] == value]
    # Write the dataframe to a new csv file
    value_df.to_csv(f"/content/drive/MyDrive/github/collegeproject/datasets/unique_crops_south/{'crop'}_{value}.csv", index=False)