In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.utils import to_categorical
import tensorflow as tf
from tensorflow import keras

In [2]:
df=pd.read_csv("/content/drive/MyDrive/github/collegeproject/datasets/south_crops.csv")
df.columns

Index(['State_Name', 'District_Name', 'Crop_Year', 'Season', 'Area',
       'Production', 'Temperature', 'PH', 'Rainfall', 'Sowing Temp',
       'Harvest Temp', 'Phosphorous', 'Nitrogen', 'Potash', 'crop'],
      dtype='object')

In [3]:
df=df.iloc[:,[4,6,8]]

In [4]:
df.columns

Index(['Area', 'Temperature', 'Rainfall'], dtype='object')

In [5]:
df.describe()

                Area   Temperature      Rainfall
count   19354.000000  19354.000000  19354.000000
mean    17754.839085     25.310872     80.548313
std     44034.176532      4.515875     55.583544
min         0.240000     14.062558      7.501110
25%       237.000000     22.293138     54.321871
50%      2146.500000     25.380890     67.638047
75%     14327.250000     28.275284     92.931267
max    877029.000000     39.895564    299.865346

In [6]:
df.shape

(19354, 3)

In [7]:
df['crop'].unique()

KeyError: ignored

In [8]:
df.dtypes

Area           float64
Temperature    float64
Rainfall       float64
dtype: object

In [9]:
crops=pd.read_csv("/content/drive/MyDrive/github/collegeproject/datasets/south_crops.csv")

In [10]:
crops.columns

Index(['State_Name', 'District_Name', 'Crop_Year', 'Season', 'Area',
       'Production', 'Temperature', 'PH', 'Rainfall', 'Sowing Temp',
       'Harvest Temp', 'Phosphorous', 'Nitrogen', 'Potash', 'crop'],
      dtype='object')

In [11]:
# Get the unique values of the column you want to split the data by
column_values = crops['crop'].unique()
# Loop over the unique values of the column
for value in column_values:
    # Create a dataframe for each unique value
    value_df = crops[crops['crop'] == value]
    # Write the dataframe to a new csv file
    value_df.to_csv(f"/content/drive/MyDrive/github/collegeproject/datasets/unique_crops_south/{'crop'}_{value}.csv", index=False)